version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    hostname: kittygram_pg
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: rukiqq/kittygram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend/collected_static
      - media:/backend/media
    environment:
      WAIT_HOSTS: kittygram_pg:5432
  frontend:
    image: rukiqq/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: rukiqq/kittygram_gateway
    depends_on:
      - backend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
